<?php get_header(); ?>

<!-- HERO -->
<section class="hero">
  <div class="hero-bg"></div>
  <div class="hero-grid"></div>
  <div class="hero-content">
    <div class="hero-eyebrow"><span style="display:inline-block;width:32px;height:2px;background:var(--teal);border-radius:2px;flex-shrink:0;"></span> Intelligence Applied</div>
    <h1>Move Beyond Data.<br/>Build an <span class="hl">Intelligence</span><br/>Platform.</h1>
    <p>With deep domain expertise, our practicing functional leaders deliver outcomes-led solutions that transform healthcare data into measurable business value.</p>
    <div class="hero-actions">
      <a href="<?php echo sdsol_url('/contact/'); ?>" class="btn-primary">Talk to an AI Outcomes Expert</a>
      <a href="<?php echo sdsol_url('/success-stories/'); ?>" class="btn-ghost">View Success Stories</a>
    </div>
    <div class="hero-partners">
      <div class="hero-partners-label">Trusted Technology Partners</div>
      <div class="hero-badges">
        <div class="hero-badge"><span class="badge-dot"></span> Microsoft Azure</div>
        <div class="hero-badge"><span class="badge-dot"></span> Snowflake</div>
        <div class="hero-badge"><span class="badge-dot"></span> Databricks</div>
        <div class="hero-badge"><span class="badge-dot"></span> AWS</div>
        <div class="hero-badge"><span class="badge-dot"></span> Microsoft Fabric</div>
      </div>
    </div>
  </div>
  <div class="hero-stats">
    <div class="stat-card"><div class="stat-num">30%</div><div class="stat-label">Of global data is<br/>generated by healthcare</div></div>
    <div class="stat-card"><div class="stat-num">137 TB</div><div class="stat-label">Health data produced<br/>every single day</div></div>
    <div class="stat-card"><div class="stat-num">1.2B+</div><div class="stat-label">Medical charts<br/>generated annually</div></div>
  </div>
</section>

<!-- LOGOS TICKER -->
<div class="logos-section">
  <div class="logos-label">Technology Partners &amp; Platforms</div>
  <div class="logos-track">
    <span>Microsoft Azure</span><span>·</span><span>Microsoft Fabric</span><span>·</span><span>Snowflake</span><span>·</span><span>Databricks</span><span>·</span><span>AWS</span><span>·</span><span>Google Cloud</span><span>·</span><span>Tableau</span><span>·</span><span>Power BI</span><span>·</span><span>Informatica</span><span>·</span><span>Salesforce</span><span>·</span><span>Profisee</span><span>·</span><span>Talend</span><span>·</span>
    <span>Microsoft Azure</span><span>·</span><span>Microsoft Fabric</span><span>·</span><span>Snowflake</span><span>·</span><span>Databricks</span><span>·</span><span>AWS</span><span>·</span><span>Google Cloud</span><span>·</span><span>Tableau</span><span>·</span><span>Power BI</span><span>·</span><span>Informatica</span><span>·</span><span>Salesforce</span><span>·</span><span>Profisee</span><span>·</span><span>Talend</span><span>·</span>
  </div>
</div>

<!-- SERVICES -->
<section id="services">
  <div class="section-wrap">
    <div class="services-header reveal">
      <div>
        <span class="section-tag">What We Do</span>
        <div class="section-title">End-to-End Data<br/>Solutions That Deliver</div>
      </div>
      <p class="section-sub">From strategy to implementation to managed services — we cover every stage of your data journey with deep healthcare domain expertise at the core.</p>
    </div>
    <div class="services-grid reveal">
      <div class="service-card">
        <div class="service-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="8" rx="2"/><rect x="2" y="14" width="20" height="8" rx="2"/><line x1="6" y1="6" x2="6.01" y2="6"/><line x1="6" y1="18" x2="6.01" y2="18"/></svg></div>
        <h3>Data Infrastructure + Architecture</h3>
        <p>Design and build scalable, modern data platforms on the cloud. We architect solutions that grow with your organization and eliminate data silos.</p>
        <a href="<?php echo sdsol_url('/service-data-infrastructure/'); ?>" class="service-link">Learn More</a>
      </div>
      <div class="service-card">
        <div class="service-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="m9 12 2 2 4-4"/></svg></div>
        <h3>Data Governance</h3>
        <p>Establish robust frameworks with Microsoft Purview and best-in-class tools. Ensure compliance, quality, and trust across all data assets.</p>
        <a href="<?php echo sdsol_url('/service-data-governance/'); ?>" class="service-link">Learn More</a>
      </div>
      <div class="service-card">
        <div class="service-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><path d="M6 21V9a9 9 0 0 0 9 9"/></svg></div>
        <h3>Data Engineering Services</h3>
        <p>Expert pipelines, ETL/ELT workflows, and data integration built for reliability. We operationalize your data products so insights are always fresh.</p>
        <a href="<?php echo sdsol_url('/service-data-engineering/'); ?>" class="service-link">Learn More</a>
      </div>
      <div class="service-card">
        <div class="service-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg></div>
        <h3>Data Analytics Services</h3>
        <p>Turn raw data into actionable insights. From dashboards to predictive models and AI-powered analytics — we close the gap between data and decisions.</p>
        <a href="<?php echo sdsol_url('/service-data-analytics/'); ?>" class="service-link">Learn More</a>
      </div>
      <div class="service-card">
        <div class="service-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M15 2v2M9 2v2M2 15h2M2 9h2M22 15h-2M22 9h-2M15 22v-2M9 22v-2"/></svg></div>
        <h3>AI / ML Solutions</h3>
        <p>Deploy machine learning models and generative AI solutions tailored to healthcare workflows — from readmission prediction to intelligent automation.</p>
        <a href="<?php echo sdsol_url('/service-ai-ml/'); ?>" class="service-link">Learn More</a>
      </div>
      <div class="service-card">
        <div class="service-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/></svg></div>
        <h3>Advisory &amp; Strategy</h3>
        <p>Strategic roadmapping and advisory services from practitioners who have led real healthcare data transformations — not just technology generalists.</p>
        <a href="<?php echo sdsol_url('/service-advisory/'); ?>" class="service-link">Learn More</a>
      </div>
    </div>
  </div>
</section>

<!-- TESTIMONIAL -->
<div class="testimonial-wrap reveal">
  <div class="testimonial-inner">
    <div class="testimonial-quote">SD Sol brings something rare — a team that truly understands healthcare operations AND modern data platforms. They didn't just deliver technology; they delivered outcomes that changed how we make decisions.</div>
    <div class="testimonial-author">
      <div class="author-avatar">CM</div>
      <div class="author-info">
        <strong>Chief Medical Officer</strong>
        <span>Regional Health System, New Jersey</span>
      </div>
    </div>
  </div>
</div>

<!-- INDUSTRIES -->
<section id="industries">
  <div class="section-wrap alt">
    <div class="industries-header reveal">
      <span class="section-tag">Our Focus</span>
      <div class="section-title">Healthcare Is Where We Go Deep</div>
      <p class="section-sub">The healthcare ecosystem generates over 30% of global data volume. We help organizations unlock that potential — moving from data abundance to clinical and operational intelligence.</p>
    </div>
    <div class="card-grid-4 reveal">
      <div class="industry-card">
        <span class="industry-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 22V9l9-7 9 7v13"/><path d="M9 22V13h6v9"/><path d="M9 8h6"/><path d="M12 5v6"/></svg></span>
        <h3>Hospital Systems</h3>
        <p>Unified patient data platforms, clinical analytics, and operational intelligence for health networks of all sizes.</p>
        <a href="<?php echo sdsol_url('/industry-hospital-systems/'); ?>" class="learn-more">Learn More</a>
      </div>
      <div class="industry-card">
        <span class="industry-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M10 2v7.527a2 2 0 0 1-.211.896L4.72 20.55a1 1 0 0 0 .9 1.45h12.76a1 1 0 0 0 .9-1.45l-5.069-10.127A2 2 0 0 1 14 9.527V2"/><line x1="8.5" y1="2" x2="15.5" y2="2"/></svg></span>
        <h3>Life Sciences</h3>
        <p>Clinical trial analytics, regulatory data management, and R&amp;D intelligence for pharma and biotech organizations.</p>
        <a href="<?php echo sdsol_url('/industry-life-sciences/'); ?>" class="learn-more">Learn More</a>
      </div>
      <div class="industry-card">
        <span class="industry-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="22" x2="21" y2="22"/><line x1="6" y1="18" x2="6" y2="11"/><line x1="10" y1="18" x2="10" y2="11"/><line x1="14" y1="18" x2="14" y2="11"/><line x1="18" y1="18" x2="18" y2="11"/><polygon points="12 2 20 7 4 7"/></svg></span>
        <h3>Payers &amp; Insurers</h3>
        <p>HEDIS quality measures, claims analytics, member 360 views, and value-based care reporting.</p>
        <a href="<?php echo sdsol_url('/industry-payers/'); ?>" class="learn-more">Learn More</a>
      </div>
      <div class="industry-card">
        <span class="industry-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></span>
        <h3>Population Health</h3>
        <p>Risk stratification, care gap identification, and social determinants of health analytics to improve outcomes at scale.</p>
        <a href="<?php echo sdsol_url('/industry-healthcare/'); ?>" class="learn-more">Learn More</a>
      </div>
    </div>
  </div>
</section>

<!-- SUCCESS STORIES -->
<section id="stories">
  <div class="section-wrap">
    <div class="stories-header reveal">
      <div>
        <span class="section-tag">Proven Results</span>
        <div class="section-title">Success Stories</div>
      </div>
      <a href="<?php echo sdsol_url('/success-stories/'); ?>" class="btn-ghost">All Case Studies</a>
    </div>
    <div class="card-grid-3">
      <a href="<?php echo sdsol_url('/success-stories/'); ?>" class="story-card reveal">
        <span class="story-tag">Data Engineering</span>
        <h3>Data Engineering &amp; Analytics Transformation</h3>
        <p>Built a modern data platform enabling real-time analytics across clinical and operational data — reducing reporting time by over 60%.</p>
        <span class="story-arrow">→</span>
      </a>
      <a href="<?php echo sdsol_url('/success-stories/'); ?>" class="story-card reveal">
        <span class="story-tag">Data Governance</span>
        <h3>Data Governance with Microsoft Purview</h3>
        <p>Implemented enterprise-wide governance and stewardship framework, achieving full HIPAA compliance and improving data quality scores significantly.</p>
        <span class="story-arrow">→</span>
      </a>
      <a href="<?php echo sdsol_url('/success-stories/'); ?>" class="story-card reveal">
        <span class="story-tag">AI &amp; ML</span>
        <h3>Hospital Re-admission Prediction Using AI/ML</h3>
        <p>Deployed machine learning models predicting 30-day readmissions with 85%+ accuracy, enabling proactive care interventions and reducing penalties.</p>
        <span class="story-arrow">→</span>
      </a>
    </div>
  </div>
</section>

<!-- TECH -->
<section id="tech">
  <div class="section-wrap alt">
    <div class="tech-header reveal">
      <span class="section-tag">Technology Expertise</span>
      <div class="section-title">Built on the Best Stack</div>
      <p class="section-sub">We cover a wide range of technologies, tools, and platforms to provide end-to-end coverage with deep expertise in each.</p>
    </div>
    <div class="tech-grid reveal">
      <span class="tech-badge">Microsoft Azure</span><span class="tech-badge">Microsoft Fabric</span><span class="tech-badge">Snowflake</span><span class="tech-badge">Databricks</span><span class="tech-badge">AWS</span><span class="tech-badge">Amazon Redshift</span><span class="tech-badge">Google Cloud</span><span class="tech-badge">Tableau</span><span class="tech-badge">Power BI</span><span class="tech-badge">Qlik</span><span class="tech-badge">MicroStrategy</span><span class="tech-badge">Informatica</span><span class="tech-badge">Talend</span><span class="tech-badge">Hadoop</span><span class="tech-badge">Kubernetes</span><span class="tech-badge">MongoDB</span><span class="tech-badge">Python</span><span class="tech-badge">R / R Studio</span><span class="tech-badge">Salesforce</span><span class="tech-badge">Profisee</span><span class="tech-badge">Microsoft Purview</span>
    </div>
  </div>
</section>

<!-- ABOUT STRIP -->
<section id="about">
  <div class="section-wrap">
    <div class="about-inner">
      <div class="about-visual reveal">
        <div class="about-quote">"A unique intersection of domain, functional &amp; technical expertise."</div>
        <div class="about-meta"><span class="about-dot"></span> SD Sol — Somerset, NJ</div>
      </div>
      <div class="reveal">
        <span class="section-tag">Who We Are</span>
        <div class="section-title">Delivering Excellence<br/>Through Innovation</div>
        <p class="section-sub" style="margin-bottom:2.25rem;">We take a unique approach by leveraging innovative technologies and agile methodologies. Our practicing functional leaders enable outcomes-led solutions — using technology as an enabler to drive lasting business value.</p>
        <div class="pillars">
          <div class="pillar"><div class="pillar-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg></div><div><h4>Outcomes-Led Delivery</h4><p>Every engagement is anchored to measurable business outcomes — not just technical deliverables.</p></div></div>
          <div class="pillar"><div class="pillar-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg></div><div><h4>Healthcare Domain Depth</h4><p>Practitioners with real healthcare experience, not just technology generalists.</p></div></div>
          <div class="pillar"><div class="pillar-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"/></svg></div><div><h4>Cloud-Native Expertise</h4><p>Optimized delivery on Azure, AWS, and Google Cloud — from migration to full operations.</p></div></div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- CTA STRIP -->
<div class="cta-strip reveal">
  <h2>Take the Next Step with SD Sol</h2>
  <p>Ready to transform your healthcare data into a strategic asset? Let's talk about what's possible.</p>
  <a href="<?php echo sdsol_url('/contact/'); ?>" class="btn-primary">Talk to Our Experts</a>
</div>

<?php get_footer(); ?>
